version: '3.6'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:15.7.9-ce.0'
    restart: always
    container_name: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://192.168.10.151'
        gitlab_rails['time_zone'] = 'Asia/ShangHai'
        gitlab_rails['initial_root_password'] = 'IK62gitlab'
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'



#sudo docker exec -it gitlab grep 'Password:' /etc/gitlab/initial_root_password
