#! /bin/sh
# https://man.archlinux.org/man/bspwm.1.en
# https://gist.github.com/abairo/5e2ed2faeadcc7abf43cda37826b2fbc

#pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/bspwm/autostart.sh

# 设置多显示器 使用 xrandr -q 或 bspc query -M --names 命令来查看显示器编号。
# I II III IV V VI VII VIII IX X
bspc monitor HDMI-1 -d I II III IV 
bspc monitor eDP-1 -d  V VI VII VIII 

# 光标主题
xsetroot -cursor_name Bibata-Modern-Ice

# 解决无法识别java程序
wmname LG3D


bspc config border_width         2
bspc config window_gap           4
bspc config top_padding  	 2
bspc config bottom_padding  	 2

bspc config normal_border_color "#44475a"
bspc config active_border_color "#6272a4"
bspc config focused_border_color "#8be9fd"
bspc config presel_feedback_color "#6272a4"


bspc config initial_polarity    first_child
bspc config focus_follows_pointer true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a google-chrome-unstable focus=on
bspc rule -a Rofi state=floating
bspc rule -a st-256color state=floating focus=on
bspc rule -a kitty focus=on
bspc rule -a lx-music-desktop state=tiled focus=on
bspc rule -a electron-netease-cloud-music state=tiled focus=on
#STATE := tiled|pseudo_tiled|floating|fullscreen


