
version: '3'
services:
  mysql8:
    image: mysql:8.0.33
    container_name: mysql8
    ports:
      - 3306:3306
    volumes:
       - $HOME/Containers/volumes/mysql/logs:/var/log/mysql
       - $HOME/Containers/volumes/mysql/data:/var/lib/mysql
       - $HOME/Containers/volumes/mysql/data:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: kylin
      MYSQL_USER: albert
      MYSQL_PASSWORD: kylin
    command:
      --max_connections=1000
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --lower_case_table_names=1
